import { Obra } from "../models/obra";
import { PARTITURAS } from "./partituras.json";

export const OBRAS: Obra[] = [
    {
        id: 1,
        nombre: 'Oriundos de Tlahuitoltepec',
        compositor : 'Eleazar Hernández Vásquez',
        arreglista : 'Eleazar Hernández Vásquez',
        letrista : 'Eleazar Hernández Vásquez',
        genero : 'Danzón',
        precio : 100,
        embedAudio : 'https://open.spotify.com/embed/track/7rhKh1Ool2Yel5JXmiemZB?utm_source=generator&theme=0',
        embedVideo : 'https://www.youtube.com/embed/Yn5vQ66q7os?si=9m38F_lD8ABGzzuR',
        createdAt: new Date(),
        modifiedAt: new Date(),
        partituras : PARTITURAS,
    },
    {
        id: 2,
        nombre: 'Xaab Newex',
        compositor : 'Xaab Newex',
        arreglista : 'Jose Luis Hernandez Vásquez',
        letrista : 'Jose Luis Hernandez Vásquez',
        genero : 'Marcha',
        precio : 300,
        embedAudio : 'https://open.spotify.com/embed/track/7rhKh1Ool2Yel5JXmiemZB?utm_source=generator&theme=0',
        embedVideo : 'https://www.youtube.com/embed/Yn5vQ66q7os?si=9m38F_lD8ABGzzuR',
        createdAt: new Date(),
        modifiedAt: new Date(),
        partituras : PARTITURAS,
    },
    {
        id: 3,
        nombre: 'Tu Sonrisa',
        compositor : 'Tu Sonrisa',
        arreglista : 'Pedro Hernandez Vasquez',
        letrista : 'Pedro Hernandez Vasquez',
        genero : 'Son',
        precio : 300,
        embedAudio : 'https://open.spotify.com/embed/track/7rhKh1Ool2Yel5JXmiemZB?utm_source=generator&theme=0',
        embedVideo : 'https://www.youtube.com/embed/Yn5vQ66q7os?si=9m38F_lD8ABGzzuR',
        createdAt: new Date(),
        modifiedAt: new Date(),
        partituras : PARTITURAS,
    },
    {
        id: 4,
        nombre: 'Leticia Gallardo',
        compositor : 'Compositor4',
        arreglista : 'arreglista4',
        letrista : 'letrista4',
        genero : 'genero4',
        precio : 400,
        embedAudio : 'https://open.spotify.com/embed/track/7rhKh1Ool2Yel5JXmiemZB?utm_source=generator&theme=0',
        embedVideo : 'https://www.youtube.com/embed/Yn5vQ66q7os?si=9m38F_lD8ABGzzuR',
        createdAt: new Date(),
        modifiedAt: new Date(),
        partituras : PARTITURAS,
    },
]